config/routes.rb
Rails.application.routes.draw do
 
  resources :contatos
  get 'dashboard/home'

  resources :arquivos
  resources :professores
  resources :nucleos
  resources :provas
  resources :photos
  resources :galeries
  get 'site/index'

  get 'site/equipe'

  get 'site/historia'

  get 'site/estrutura'

  get 'site/infantil'

  get 'site/fundamental_I'

  get 'site/fundamental_II'

  get 'site/medio'

  get 'site/projetos'

  get 'site/egressos'

  get 'site/calendario'

  get 'site/provas'
  post 'site/provas'

  get 'site/humanas'

  get 'site/linguas'

  get 'site/matematica'

  get 'site/biologicas'

  get 'site/natureza'

  get 'site/redacao'

  get 'site/noticias'
  
  get 'site/noticia_show'
  
  post 'site/noticia_show'

  get 'site/galeria'
  get 'site/galeria_show'
  post 'site/galeria_show'

  get 'site/contato'
  post 'site/professores'
  get 'site/professores'
  post 'site/arquivos'
  get 'site/arquivos'
  post 'site/testes'
  get 'site/testes'

  get 'site/pre_matricula'
  post 'site/pre_matricula'
  get 'site/pre_matricula_post'
  post 'site/pre_matricula_post'
  post 'site/projetos_show'
  get 'site/projetos_show'
  resources :acontecimentos
  resources :news
  resources :egressos
  resources :projetos
  resources :estruturas
  resources :calendarios
  resources :equipes
  resources :coladoradores
  resources :sliders
  get 'teste/home'

  devise_for :users
  get 'dashboard/home'
  root :to => 'site#index'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
   skip_before_filter :verify_authenticity_token
  def index
       @nucleos = Nucleo.all
       @provas = Prova.all
     @sliders = Slider.all
     @slider=Slider.first
     @news = News.order(id: :desc)
     @cont_news=0
     
  end

  def equipe
       @nucleos = Nucleo.all
       @provas = Prova.all
    @teams= Equipe.first
    @colaboradors = Coladoradore.all
  end

  def historia
       @nucleos = Nucleo.all
       @provas = Prova.all
     @historico = Acontecimento.first
  end

  def estrutura
       @nucleos = Nucleo.all
       @provas = Prova.all
       @estruturas = Estrutura.paginate(:page => params[:page])
       @estrutura = Estrutura.first
       @cont_estruturas=0
  end

  def infantil
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def fundamental_I
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def fundamental_II
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def medio   
   @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def projetos
       @nucleos = Nucleo.all
       @provas = Prova.all
      @projetos = Projeto.paginate(:page => params[:page])
  end

  def egressos
       @nucleos = Nucleo.all
       @provas = Prova.all
     @egressos = Egresso.all
  end

  def calendario
       @nucleos = Nucleo.all
       @provas = Prova.all
       @calendario = Calendario.last
  end

  def provas
       @nucleos = Nucleo.all
       @provas = Prova.all
       @id=params[:prova_id]
       @prova=Prova.find(@id)
       
  end

  def humanas
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def linguas
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def matematica
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def biologicas
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def natureza
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def redacao
       @nucleos = Nucleo.all
       @provas = Prova.all
  end

  def noticias 
   @nucleos = Nucleo.all
   
       @provas = Prova.all
       @news = News.order(id: :desc).paginate(:page => params[:page])
     
  end
  def noticia_show
       @nucleos = Nucleo.all
       @provas = Prova.all
      @id=params[:noticia_id]
      @noticia= News.find(@id)
      
      
      
  end
  
  def galeria
       @nucleos = Nucleo.all
       @provas = Prova.all
        @galeries = Galery.order(id: :desc).paginate(:page => params[:page])

  end
  def galeria_show
       @nucleos = Nucleo.all
       @provas = Prova.all
      @id=params[:galeria_id]
      @galery=Galery.find(@id)
      @photos = @galery.photos.paginate(:page => params[:page])
      @size= @galery.photos.size
      @photo = @galery.photos.build
      @foto=@galery.photos.first
       @cont_photos=0
       @contador_pagina=1
  end
  def contato
      @nucleos = Nucleo.all
      @provas = Prova.all
      @nome=params[:nome]
      @email_contato=params[:email]
      @texto=params[:texto]
      @email=Email.new
      @dados_email=DadosEmail.new
      @dados_email.destinatario="col.anglodecampinas@gmail.com"
      @dados_email.subject="Formulario de contato"
      @dados_email.body="Contato via formulario "
      @dados_email.body_html= "<h1> nome do contato: #{@contato.nome}</h1><br> email: #{@contato.email}<br> <h1>conteudo da mensagem</h1> <br> #{@contato.text.html_safe} "
      @email.send_email @dados_email
  end

  def pre_matricula
       @nucleos = Nucleo.all
       @provas = Prova.all
      

  
  end
  def pre_matricula_post
                @nucleos = Nucleo.all
        @provas = Prova.all
  
    #dados do aluno
    @serie=params[:serie]
    @turno=params[:turno]
    @ano=params[:ano]
    @nome_aluno=params[:nome_aluno]
    @naturalidade_aluno=params[:naturalidade_aluno]
    @nacionalidade_aluno=params[:nacionalidade_aluno]
    @data_nascimento_aluno=params[:data_nascimento_aluno]
    @sexo_aluno=params[:sexo_aluno]
    @cpf_aluno=params[:cpf_aluno]
    @endereco_aluno=params[:endereco_aluno]
    @complemento_aluno=params[:complemento_aluno]
    @bairro_aluno=params[:bairro_aluno]
    @cidade_aluno=params[:bairro_aluno]
    @cep_aluno=params[:cep_aluno]
    @telefone_aluno=params[:telefone_aluno]
    @celular_aluno=params[:celular_aluno]
    #dados do pai
    @nomepai=params[:nomepai]
    @rgpai=params[:rgpai]
    @endepai=params[:endepai]
    @bairropai=params[:bairropai]
    @terespai=params[:terespai]
    @wppai=params[:wppai]
    #dados mae
   @nomemae=params[:nomemae]
   @rgmae=params[:rgmae]
   @endemae=params[:endemae]
   @bairromae=params[:bairromae]
   @teresmae=params[:teresmae]
   @wpmae=params[:wpmae]
   #dados do aluno mobile
   @serie_mobile  =params[:serie_mobile]
   @turno_mobile  =params[:turno_mobile]
   @ano_mobile  =params[:ano_mobile]
   @nome_aluno_mobile  =params[:nome_aluno_mobile]
   @nacionalidade_aluno_mobile  =params[:nacionalidade_aluno_mobile]
   @naturalidade_aluno_mobile  =params[:naturalidade_aluno_mobile]
   @data_nascimento_aluno_mobile  =params[:data_nascimento_aluno_mobile]
   @sexo_aluno_mobile  =params[:sexo_aluno_mobile]
   @endereco_aluno_mobile  =params[:endereco_aluno_mobile]
   @complemento_aluno_mobile  =params[:complemento_aluno_mobile]
   @bairro_aluno_mobile  =params[:bairro_aluno_mobile]
   @cep_aluno_mobile  =params[:cep_aluno_mobile]
    @cpf_aluno_mobile  =params[:cpf_aluno_mobile]
   @cidade_aluno_mobile  =params[:cidade_aluno_mobile]
   @telefone_aluno_mobile =params[:telefone_aluno_mobile]
   @celular_aluno_mobile =params[:celular_aluno_mobile]
    @email=Email.new
    @dados_email=DadosEmail.new
    @dados_email.destinatario="lucasalemao.ns@gmail.com"
    @dados_email.subject="pré_matricula"
    @dados_email.body="dados de nome dados de sobrenome "
    @dados_email.body_html= render 'dashboard/template_contato'
    @email.send_email @dados_email

  end
 
  def projetos_show
       @nucleos = Nucleo.all
       @provas = Prova.all
    @id=params["id_projeto"]
    @projeto=Projeto.find(@id)
  end
  def professores
       @nucleos = Nucleo.all
       @provas = Prova.all
       @id=params[:nucleo_id]
       @nucleo=Nucleo.find(@id)
       @professores = @nucleo.professores.order(nome: :asc)
       @professore = @nucleo.professores.build
  end
  def arquivos
       @nucleos = Nucleo.all
       @provas = Prova.all
       @id=params[:professor_id]
       @professore=Professore.find(@id)
       @arquivos = @professore.arquivos.order(data_prioridade: :desc)
       @arquivo =@professore.arquivos.build
       @maternal=false
       @fase_1=false
       @fase_2=false
       @fase_3=false
       @primeiro=false
       @segundo=false
       @terceiro=false
       @quarto=false
       @quinto=false
       @sexto=false
       @setimo=false
       @oitavo=false
       @nono=false
       @primeiro_medio=false
       @segundo_medio=false
       @terceiro_medio=false
       
  end
  def testes
       @nucleos = Nucleo.all
       @provas = Prova.all
  
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/partials/site/_footer.html.erb
 <div class="container-fluid main-canvas-end">
            <div class="container-fluid bottombar" id="footer">Copyright © 2017 Colégio Anglo de Campinas. Todos os direitos reservados.<br>Rua Benjamin Constant, Nº 1287, Setor Campinas - Goiânia-Go<br>Fone: (62) 3291-1806 CNPJ:26895367.0001/04 E-mail: col.anglodecampinas@gmail.com
           <br>
           <br>
           <center>Desenvolvido por <a href="http://voastudio.tech/" style="color:white; background: transparent !important;" target="_blank" >Voa Studio Tech</a></center>
            </div>
          
            
         </div>
         
         <style type="text/css"> 
a:link 
{ 
text-decoration:none; 
} 
</style>

app/views/partials/site/_header.html.erb
<div class="container-fluid hidden-md hidden-sm hidden-xs topbar "id="logobar_um" >
   <%= link_to root_path,style:"background-color: transparent !important;" do %>
     <%=image_tag("img/logo.png",style:"max-height:80px;margin-left:20px;margin-top:40px;")%>
   <% end %>
   
   
   </a>
</div>
<div class="container-fluid hidden-lg hidden-xs topbar-md-sm  style_image" id="logobar_dois">
    <%= link_to root_path,style:"background-color: transparent !important;" do %>
     <%=image_tag("img/logo.png",style:"max-height:56px;margin-left:20px;margin-top:35px; ")%>
   <% end %>
</div>
<div class="container-fluid hidden-sm hidden-md hidden-lg topbar-xs  style_image" id="logobar_tres">
    <%= link_to root_path,style:"background-color: transparent !important;" do %>
     <%=image_tag("img/logo.png",style:"max-height:44px;margin-left:15px;margin-top:30px;")%>
   <% end %>
   <div class="menutoggle"> <a id="menutoggle" href="#" class="thumbnail" style="margin:0px;"> <i class="zmdi zmdi-menu zmdi-hc-2x m10"></i> </a> 
   </div>
</div>

app/views/partials/site/_home_links.html.erb
<div class="col-lg-2 hidden-md hidden-sm hidden-xs quicklinx" style="text-align:right !important;"> 
<a href="http://sisu.mec.gov.br/" target="_new" style="background-color: transparent !important;"><%=image_tag("img/sisu.jpg",style:"margin-left:25% !important;max-width:100% !important;")%> </a> 
<a href="http://enem.inep.gov.br/" target="_new"style="background-color: transparent !important;"> <%=image_tag("img/enem.png",style:"margin-left:25% !important;max-width:100% !important;")%> </a>
<a href="http://siteprouni.mec.gov.br/" target="_new" style="background-color: transparent !important;"> <%=image_tag("img/prouni.png",style:"margin-left:25% !important;max-width:100% !important;")%> </a>
<a href="https://www.ufg.br/" target="_new" style="background-color: transparent !important;"> <%=image_tag("img/ufg.png",style:"margin-left:25% !important;max-width:100% !important;")%> </a>
<a href="https://www.ifg.edu.br/" target="_new" style="background-color: transparent !important;"><%=image_tag("img/ifgoias.png",style:"margin-left:25% !important;max-width:100% !important;")%></a> 
<a href="https://www.ifgoiano.edu.br/home/" target="_new"style="background-color: transparent !important;"><%=image_tag("img/ifgoiano.png",style:"margin-left:25% !important;max-width:100% !important;")%> </a> 
<a href="http://www.ueg.br/" target="_new"style="background-color: transparent !important;"> <%=image_tag("img/ueg.png",style:"margin-left:25% !important;max-width:100% !important;")%></a> 
<a href="https://www.unb.br/" target="_new"style="background-color: transparent !important;"> <%=image_tag("img/unb.png",style:"margin-left:25% !important;max-width:100% !important;")%> </a>
</div>


 
</div>
</div>

app/views/partials/site/_home_maps.html.erb
<div class="col-sm-6"> <iframe width="100%" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBOd_9RgyeENqXLhh3awsdcpGe5JZKupUY&q=Colégio%20Anglo%20Campinas" allowfullscreen></iframe></div>

app/views/partials/site/_home_noticias.html.erb
 <div class="container">
            <div class="row headings">
                
                <% @news.each do |news| %>
               <%@cont_news+=1%>
               <%if @cont_news<=7%>
              
               <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12 headlist text-center">
                  <div class="headliner" style="margin-left: 0px !important;margin-right: 0px !important;">
                        <a href="home/noticia/1.html">
                            <div class="picture">   <%= link_to (image_tag news.capa.url,style:"width=100%",class:"img-responsive"), site_noticia_show_path(:noticia_id =>news.id), :method => :post %></div>
                           <h3 style="text-transform:uppercase;"><%= news.titulo.html_safe %></h3>
                           <p><%= news.abstract.html_safe %></p>
                        </a>
                  </div>
               </div>
              <%end%>
               <%end%>

               
               
    

app/views/partials/site/_home_slider.html.erb
 <div class="row">
  <div class="col-md-12">
      <div class="container-fluid main-canvas">
   <div class="jumbo bg-black">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
         <div class="carousel-inner">
            <div class="item active">
                <a href=<%=@slider.link%>>
              <center>  <%=image_tag @slider.photo.url,class:"img-responsive"%></center>
                </a>
             </div>
              <% @sliders.each do |slider| %>
               <%if slider.id!=@slider.id%>
               <div class="item">
                
                    <a href=<%=slider.link%>>
                <center>   <%=(image_tag slider.photo.url,class:"img-responsive")%></center>
                   </a>
             
                </div>
                   <%end%>  
            <% end %>
       
         </div>
         <a class="left carousel-control" href="#myCarousel" data-slide="prev" style="background: transparent !important"><%=fa_icon "arrow-left fa-5",style:"margin-top:50%;" %>   </i> <span class="sr-only">Previous</span> </a> <a class="right carousel-control" href="#myCarousel" data-slide="next" style="background: transparent !important"> <%=fa_icon "arrow-right fa-5",style:"margin-top:50%;" %> <span class="sr-only">Next</span> </a> 
      </div>
   </div>
</div>
  </div>
 
</div>

app/views/partials/site/_home_social.html.erb
 <div class="container" style="margin-top:60px;margin-bottom:60px;">
            <div class="row headings">
               <div class="col-sm-6" style="min-height:450px;vertical-align:bottom;display: table-cell;">
                  <div style="position:relative;bottom:0px;">
                      <a href="https://www.facebook.com/anglodecampinasGO/"  target="_blank" style="background: transparent !important;">  <img src="https://anglo1.000webhostapp.com/public_html/../_public/_front/main/img/media_fb.png" style="max-height:80px;"/></a>
                    
                      <a href="https://www.instagram.com/ferasanglo/"  target="_blank" style="background: transparent !important;"><img src="https://anglo1.000webhostapp.com/public_html/../_public/_front/main/img/media_insta.png" style="max-height:80px;"/></a>
                  </div>
               </div>
             <%=render"partials/site/home_maps"%>
            </div>
         </div>

app/views/partials/site/_menu.html.erb
<div class="menubar hidden-xs">
               <ul>
                  <li><%= link_to "Home", site_index_path %></li>
                  <li>
                     <a href="#" id="colegiomenu" >O Colégio</a> 
                     <ul id="menucolegio" class="menu second-level" style="display: none; z-index: 9999;">
                        <li><%= link_to "Equipe", site_equipe_path %></li>
                        <li><%= link_to "História", site_historia_path %></li>
                        <li><%= link_to "Estrutura", site_estrutura_path %></li>
                        <li>
                           <a href="#" id="professoresmenu">Professores</a> 
                           <ul id="menuprofessores" class="menu third-level" style="display: none; z-index: 9999;">
                               <% @nucleos.each do |nucleo| %>
                                    <li>
                                        <%= link_to nucleo.titulo, site_professores_path(:nucleo_id => nucleo.id), :method => :post %>
                                     
                                    </li>
                                  
                                    
                                    
     
                                         
                                     <% end %>
                           </ul>
                        </li>
                        <li><a class="secleveler" href="https://portaldoprofessor.escolarmanageronline.com.br/Login" target="_new" >Portal do Professor</a></li>
                     </ul>
                  </li>
                  <li>
                     <a href="#" id="alunosmenu">Estudantes</a> 
                     <ul id="menualunos" class="menu second-level" style="display: none; z-index: 9999;">
                        <li>
                           <a href="#" id="enemmenu">ENEM</a> 
                           <ul id="menuenem" class="menu third-level" style="display: none; z-index: 9999;">
                               <% @provas.each do |prova| %>
    

   
                              <li>
                                 <%= link_to prova.titulo, site_provas_path(:prova_id => prova.id), :method => :post %>
                                   
                              </li>
                               <% end %>
                           </ul>
                        </li>
                        <li> <%= link_to "Projetos", site_projetos_path %></li>
                        <li> <%= link_to "Egressos", site_egressos_path %></li>
                        <li> <%= link_to "Calendário", site_calendario_path %></li>
                     </ul>
                  </li>
                  <li>
                     <a id="noticiasmenu" href="#">Notícias</a> 
                     <ul id="menunoticias" class="menu second-level" style="display: none; z-index: 9999;">
                        <li> <%= link_to "Notícias", site_noticias_path %></li>
                        <li>
                           <%= link_to "Galeria de fotos", site_galeria_path %>
                        </li>
                     </ul>
                  </li>
                  <li> <%= link_to "Pré matricula", site_pre_matricula_path %></li>
                       <li> <%= link_to 'Contato', new_contato_path %></li>
               </ul>
            </div>
            <div id="mainmenu" class="menubar-xs hidden-sm hidden-md hidden-lg">
               <ul style="margin:0px !important;padding:0px !important; width:100% !important">
                  <li><a href="index.html">Home</a></li>
                  <li>
                     <a href="#" data-toggle="collapse" data-target="#colegioaccord">O Colégio</a> 
                     <div id="colegioaccord" class="collapse">
                        <br><br> 
                        <ul style="margin:0px !important;padding:0px !important; width:100% !important">
                           <li> <%= link_to "Equipe", site_equipe_path %></li>
                           <li> <%= link_to "História", site_historia_path %></li>
                           <li> <%= link_to "Estrutura",site_estrutura_path %></li>
                           <li>
                              <a href="#" data-toggle="collapse" data-target="#profaccord" >Professores</a> 
                              <div id="profaccord" class="collapse">
                                 <br><br> 
                                 <ul style="margin:0px !important;padding:0px !important; width:100% !important" >
                                     <% @nucleos.each do |nucleo| %>
                                    <li>
                                        <%= link_to nucleo.titulo, site_professores_path(:nucleo_id => nucleo.id), :method => :post %>
                                     
                                    </li>
                                  
                                    
                                    
     
                                         
                                     <% end %>
                                 </ul>
                                 <br><br> 
                              </div>
                           </li>
                           <li><a href="https://portaldoprofessor.escolarmanageronline.com.br/Login" target="_new" >Portal do Professor</a></li>
                        </ul>
                        <br><br> 
                     </div>
                  </li>
                  <li>
                     <a href="#" data-toggle="collapse" data-target="#alunosaccord">Estudantes</a> 
                     <div id="alunosaccord" class="collapse">
                        <br><br> 
                        <ul style="margin:0px !important;padding:0px !important; width:100% !important">
                           <li>
                              <a data-toggle="collapse" data-target="#enemaccord" href="#" >ENEM</a> 
                              <div id="enemaccord" class="collapse">
                                 <br><br> 
                                 <ul style="margin:0px !important;padding:0px !important; width:100% !important">
                                    <% @nucleos.each do |nucleo| %>
                                    <li>
                                        <%= link_to nucleo.titulo, site_professores_path(:nucleo_id => nucleo.id), :method => :post %>
                                     
                                    </li>
                                  
                                    
                                    
     
                                         
                                     <% end %>
                                 </ul>
                                 <br><br> 
                              </div>
                           </li>
                           <li> <%= link_to "Projetos", site_projetos_path %></li>
                           <li> <%= link_to "Egressos", site_egressos_path %><li>
                           <li> <%= link_to "Calendario", site_calendario_path %></li>
                        </ul>
                        <br><br> 
                     </div>
                  </li>
                  <li>
                     <a href="#" data-toggle="collapse" data-target="#noticiasaccord">Notícias</a> 
                     <div id="noticiasaccord" class="collapse">
                        <br><br> 
                        <ul style="margin:0px !important;padding:0px !important; width:100% !important">
                           <li> <%= link_to "Notícias", site_noticias_path %></li>
                           <li>
                               <%= link_to "Galeria de Fotos", site_galeria_path %>
                           </li>
                        </ul>
                        <br><br> 
                     </div>
                  </li>
                  <li> <%= link_to ' Contato', new_contato_path %></li>
                    <li> <%= link_to "Pré matricula", site_pre_matricula_path %></li>
               </ul>
            </div>
         </div>

app/views/partials/site/_noticias.html.erb
 <div class="container">
            <div class="row headings">
                <% @news.each do |news| %>
               
               <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12 headlist text-center">
                  <div class="headliner" style="margin-left: 0px !important;margin-right: 0px !important;">
                       
                           <div class="picture">   <%= link_to (image_tag news.capa.url,style:"width=100%",class:"img-responsive"), site_noticia_show_path(:noticia_id =>news.id), :method => :post %></div>
                          
                           <h3 style="text-transform:uppercase;"><%= news.titulo.html_safe %></h3>
                           <p><%= news.abstract.html_safe %></p>
                       
                  </div>
               </div>
              
               <%end%>
             </div>
</div>
 <center>  <%= will_paginate @news %></center>
               
    