config/routes.rb
Rails.application.routes.draw do
 
  resources :contatos
  get 'dashboard/home'

  resources :arquivos
  resources :professores
  resources :nucleos
  resources :provas
  resources :photos
  resources :galeries
  get 'site/index'

  get 'site/equipe'

  get 'site/historia'

  get 'site/estrutura'

  get 'site/infantil'

  get 'site/fundamental_I'

  get 'site/fundamental_II'

  get 'site/medio'

  get 'site/projetos'

  get 'site/egressos'

  get 'site/calendario'

  get 'site/provas'
  post 'site/provas'

  get 'site/humanas'

  get 'site/linguas'

  get 'site/matematica'

  get 'site/biologicas'

  get 'site/natureza'

  get 'site/redacao'

  get 'site/noticias'
  
  get 'site/noticia_show'
  
  post 'site/noticia_show'

  get 'site/galeria'
  get 'site/galeria_show'
  post 'site/galeria_show'

  get 'site/contato'
  post 'site/professores'
  get 'site/professores'
  post 'site/arquivos'
  get 'site/arquivos'
  post 'site/testes'
  get 'site/testes'

  get 'site/pre_matricula'
  post 'site/pre_matricula'
  get 'site/pre_matricula_post'
  post 'site/pre_matricula_post'
  post 'site/projetos_show'
  get 'site/projetos_show'
  resources :acontecimentos
  resources :news
  resources :egressos
  resources :projetos
  resources :estruturas
  resources :calendarios
  resources :equipes
  resources :coladoradores
  resources :sliders
  get 'teste/home'

  devise_for :users
  get 'dashboard/home'
  root :to => 'site#index'

end

app/models/nucleo.rb
class Nucleo < ActiveRecord::Base
    has_many :professores
end

app/controllers/nucleos_controller.rb
class NucleosController < ApplicationController
   before_action :authenticate_user!
    layout'dashboard'
  before_action :set_nucleo, only: [:show, :edit, :update, :destroy]

  # GET /nucleos
  # GET /nucleos.json
  def index
    @nucleos = Nucleo.all
  end

  # GET /nucleos/1
  # GET /nucleos/1.json
  def show
    @professores = @nucleo.professores.all
    @professore = @nucleo.professores.build
  end

  # GET /nucleos/new
  def new
    @nucleo = Nucleo.new
  end

  # GET /nucleos/1/edit
  def edit
  end

  # POST /nucleos
  # POST /nucleos.json
  def create
    @nucleo = Nucleo.new(nucleo_params)

    respond_to do |format|
      if @nucleo.save
        format.html { redirect_to @nucleo, notice: 'Nucleo was successfully created.' }
        format.json { render :show, status: :created, location: @nucleo }
      else
        format.html { render :new }
        format.json { render json: @nucleo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nucleos/1
  # PATCH/PUT /nucleos/1.json
  def update
    respond_to do |format|
      if @nucleo.update(nucleo_params)
        format.html { redirect_to @nucleo, notice: 'Nucleo was successfully updated.' }
        format.json { render :show, status: :ok, location: @nucleo }
      else
        format.html { render :edit }
        format.json { render json: @nucleo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nucleos/1
  # DELETE /nucleos/1.json
  def destroy
    @nucleo.destroy
    respond_to do |format|
      format.html { redirect_to nucleos_url, notice: 'Nucleo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nucleo
      @nucleo = Nucleo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nucleo_params
      params.require(:nucleo).permit(:titulo, :descricao)
    end
end

app/helpers/nucleos_helper.rb
module NucleosHelper
end

app/views/nucleos/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Cadastrar nucleo de ensino</h3>
  </div>
  <div class="panel-body">
    <%= form_for(@nucleo) do |f| %>
  <% if @nucleo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nucleo.errors.count, "error") %> prohibited this nucleo from being saved:</h2>

      <ul>
      <% @nucleo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>
</div>


    

app/views/nucleos/edit.html.erb
<h1>Editar nucleo de ensino</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @nucleo,class:"btn btn-primary" %> |
<%= link_to 'Voltar', nucleos_path ,class:"btn btn-default"%>

app/views/nucleos/index.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Novo nucleo', new_nucleo_path, class:"btn btn-primary" %>
<hr>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Lista de nucleos</h3>
  </div>
  <div class="panel-body">
<table class="table">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nucleos.each do |nucleo| %>
      <tr>
        <td><%= nucleo.titulo %></td>
        <td><%= nucleo.descricao.html_safe %></td>
        <td><%= link_to 'Mostrar', nucleo ,class:"btn btn-success"%></td>
        <td><%= link_to 'Editar', edit_nucleo_path(nucleo), class:"btn btn-warning" %></td>
        <td><%= link_to 'Apagar', nucleo, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

app/views/nucleos/new.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', nucleos_path,class:"btn btn-default" %>

app/views/nucleos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @nucleo.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @nucleo.descricao.html_safe %>
</p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Professores desse nucleo</h3>
  </div>
  <div class="panel-body">
 <table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Disciplina</th>
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professores.each do |professore| %>
      <tr>
        <td><%= professore.nome %></td>
        <td><%= professore.disciplina %></td>
        
        <td><%= link_to 'Mostrar', professore,class:"btn btn-success" %></td>
        <td><%= link_to 'Editar', edit_professore_path(professore),class:"btn btn-warning" %></td>
        <td><%= link_to 'Apagar', professore, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>
  
  </div>
</div>

    <%= render 'professores/form' %>
<%= link_to 'Editar', edit_nucleo_path(@nucleo),class:"btn btn-warning" %> |
<%= link_to 'Voltar', nucleos_path,class:"btn btn-default" %>