config/routes.rb
Rails.application.routes.draw do
 
  resources :contatos
  get 'dashboard/home'

  resources :arquivos
  resources :professores
  resources :nucleos
  resources :provas
  resources :photos
  resources :galeries
  get 'site/index'

  get 'site/equipe'

  get 'site/historia'

  get 'site/estrutura'

  get 'site/infantil'

  get 'site/fundamental_I'

  get 'site/fundamental_II'

  get 'site/medio'

  get 'site/projetos'

  get 'site/egressos'

  get 'site/calendario'

  get 'site/provas'
  post 'site/provas'

  get 'site/humanas'

  get 'site/linguas'

  get 'site/matematica'

  get 'site/biologicas'

  get 'site/natureza'

  get 'site/redacao'

  get 'site/noticias'
  
  get 'site/noticia_show'
  
  post 'site/noticia_show'

  get 'site/galeria'
  get 'site/galeria_show'
  post 'site/galeria_show'

  get 'site/contato'
  post 'site/professores'
  get 'site/professores'
  post 'site/arquivos'
  get 'site/arquivos'
  post 'site/testes'
  get 'site/testes'

  get 'site/pre_matricula'
  post 'site/pre_matricula'
  get 'site/pre_matricula_post'
  post 'site/pre_matricula_post'
  post 'site/projetos_show'
  get 'site/projetos_show'
  resources :acontecimentos
  resources :news
  resources :egressos
  resources :projetos
  resources :estruturas
  resources :calendarios
  resources :equipes
  resources :coladoradores
  resources :sliders
  get 'teste/home'

  devise_for :users
  get 'dashboard/home'
  root :to => 'site#index'

end

app/models/galery.rb
class Galery < ActiveRecord::Base
     has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
      validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
     self.per_page = 8
     has_many :photos
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
   before_action :authenticate_user!
    layout'dashboard'
  before_action :set_galery, only: [:show, :edit, :update, :destroy]

  # GET /galeries
  # GET /galeries.json
  def index
    @galeries = Galery.all
  end

  # GET /galeries/1
  # GET /galeries/1.json
  def show
    @photos = @galery.photos.all
    @photo = @galery.photos.build
   
  end

  # GET /galeries/new
  def new
    @galery = Galery.new
  end

  # GET /galeries/1/edit
  def edit
  end

  # POST /galeries
  # POST /galeries.json
  def create
    @galery = Galery.new(galery_params)

    respond_to do |format|
      if @galery.save
        format.html { redirect_to @galery, notice: 'Galery was successfully created.' }
        format.json { render :show, status: :created, location: @galery }
      else
        format.html { render :new }
        format.json { render json: @galery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeries/1
  # PATCH/PUT /galeries/1.json
  def update
    respond_to do |format|
      if @galery.update(galery_params)
        format.html { redirect_to @galery, notice: 'Galery was successfully updated.' }
        format.json { render :show, status: :ok, location: @galery }
      else
        format.html { render :edit }
        format.json { render json: @galery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeries/1
  # DELETE /galeries/1.json
  def destroy
    @galery.destroy
    respond_to do |format|
      format.html { redirect_to galeries_url, notice: 'Galery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galery
      @galery = Galery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galery_params
      params.require(:galery).permit(:titulo, :data,:photo)
    end
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/views/galeries/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Criar galeria</h3>
  </div>
  <div class="panel-body">
   <%= form_for @galery, :html => { multipart: true } do |f| %>
  <% if @galery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galery.errors.count, "error") %> prohibited this galery from being saved:</h2>

      <ul>
      <% @galery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
   <%= f.file_field :photo %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>
</div>

app/views/galeries/edit.html.erb
<h1>Editar Galeria</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @galery,class:"btn btn-default" %> |
<%= link_to 'Apagar', galeries_path ,class:"btn btn-default"%>

app/views/galeries/index.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'criar galeria', new_galery_path,class:"btn btn-success" %>
<hr>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Lista de galerias</h3>
  </div>
  <div class="panel-body">
   <table class="table">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galeries.each do |galery| %>
      <tr>
        <td><%= galery.titulo %></td>
        <td><%= galery.data %></td>
        <td><%= link_to 'mostrar', galery,class:"btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_galery_path(galery),class:"btn btn-warning" %></td>
        <td><%= link_to 'Apagar', galery, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>

app/views/galeries/new.html.erb
<h1>Nova galeria</h1>

<%= render 'form' %>

<%= link_to 'Voltar', galeries_path,class:"btn btn-default" %>

app/views/galeries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @galery.titulo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @galery.data %>
</p>

<h3>Photos dessa galeria</h3>
 
    <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Fotos desta galeria</h3>
  </div>
  <div class="panel-body">
    <div class="row">
       <% @photos.each do |photo| %>
  <div class="col-md-4">
    <div class="card" >
    <%= image_tag photo.foto.url , class:"card-img-top img-responsive"%>
 
  <div class="card-block">
    <h4 class="card-title"><%= photo.nome %></h4>
        <td><%= link_to 'Mostrar', photo ,class:"btn btn-success"%></td>
        <td><%= link_to 'Editar', edit_photo_path(photo),class:"btn btn-warning" %></td>
        <td><%= link_to 'Apagar', photo, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
  </div>
</div>
  </div>
  <% end %>
</div>
 
  
     
        
      
   
  </div>
</div>
<%= render 'photos/form' %>







<%= link_to 'Editar', edit_galery_path(@galery),class:"btn btn-warning" %> |
<%= link_to 'Voltar', galeries_path ,class:"btn btn-default"%>