config/routes.rb
Rails.application.routes.draw do
 
  resources :contatos
  get 'dashboard/home'

  resources :arquivos
  resources :professores
  resources :nucleos
  resources :provas
  resources :photos
  resources :galeries
  get 'site/index'

  get 'site/equipe'

  get 'site/historia'

  get 'site/estrutura'

  get 'site/infantil'

  get 'site/fundamental_I'

  get 'site/fundamental_II'

  get 'site/medio'

  get 'site/projetos'

  get 'site/egressos'

  get 'site/calendario'

  get 'site/provas'
  post 'site/provas'

  get 'site/humanas'

  get 'site/linguas'

  get 'site/matematica'

  get 'site/biologicas'

  get 'site/natureza'

  get 'site/redacao'

  get 'site/noticias'
  
  get 'site/noticia_show'
  
  post 'site/noticia_show'

  get 'site/galeria'
  get 'site/galeria_show'
  post 'site/galeria_show'

  get 'site/contato'
  post 'site/professores'
  get 'site/professores'
  post 'site/arquivos'
  get 'site/arquivos'
  post 'site/testes'
  get 'site/testes'

  get 'site/pre_matricula'
  post 'site/pre_matricula'
  get 'site/pre_matricula_post'
  post 'site/pre_matricula_post'
  post 'site/projetos_show'
  get 'site/projetos_show'
  resources :acontecimentos
  resources :news
  resources :egressos
  resources :projetos
  resources :estruturas
  resources :calendarios
  resources :equipes
  resources :coladoradores
  resources :sliders
  get 'teste/home'

  devise_for :users
  get 'dashboard/home'
  root :to => 'site#index'

end

app/models/professore.rb
class Professore < ActiveRecord::Base
    belongs_to :nucleo
    has_many :arquivos
     has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
      validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/controllers/professores_controller.rb
class ProfessoresController < ApplicationController
   before_action :authenticate_user!
    layout'dashboard'
  before_action :set_professore, only: [:show, :edit, :update, :destroy]

  # GET /professores
  # GET /professores.json
  def index
    @professores = Professore.all
  end

  # GET /professores/1
  # GET /professores/1.json
  def show
     @arquivos = @professore.arquivos.all
    @arquivo =@professore.arquivos.build
  end

  # GET /professores/new
  def new
    @professore = Professore.new
  end

  # GET /professores/1/edit
  def edit
  end

  # POST /professores
  # POST /professores.json
  def create
    @professore = Professore.new(professore_params)

    respond_to do |format|
      if @professore.save
        format.html { redirect_to @professore, notice: 'Professore was successfully created.' }
        format.json { render :show, status: :created, location: @professore }
      else
        format.html { render :new }
        format.json { render json: @professore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professores/1
  # PATCH/PUT /professores/1.json
  def update
    respond_to do |format|
      if @professore.update(professore_params)
        format.html { redirect_to @professore, notice: 'Professore was successfully updated.' }
        format.json { render :show, status: :ok, location: @professore }
      else
        format.html { render :edit }
        format.json { render json: @professore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professores/1
  # DELETE /professores/1.json
  def destroy
    @professore.destroy
    respond_to do |format|
      format.html { redirect_to nucleo_path(@professore.nucleo_id), notice: 'Professore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professore
      @professore = Professore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professore_params
      params.require(:professore).permit(:nome, :disciplina, :descricao, :nucleo_id,:photo)
    end
end

app/helpers/professores_helper.rb
module ProfessoresHelper
end

app/views/professores/_form.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Cadastrar professor</h3>
  </div>
  <div class="panel-body">
   <%= form_for @professore, :html => { multipart: true } do |f| %>

  <% if @professore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professore.errors.count, "error") %> prohibited this professore from being saved:</h2>

      <ul>
      <% @professore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :disciplina %><br>
    <%= f.text_field :disciplina %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
   <div class="field">
    <%= f.label :photo %><br>
     <%= f.file_field :photo %>
  </div>
 

 <%= f.hidden_field :nucleo_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>
</div>

app/views/professores/edit.html.erb
<h1>Editar professor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @professore,class:"btn btn-primary" %> |
<%= link_to "Voltar", nucleo_path(@professore.nucleo_id),class:"btn btn-default" %>

app/views/professores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Professores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Disciplina</th>
      <th>Descricao</th>
      <th>Nucleo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professores.each do |professore| %>
      <tr>
        <td><%= professore.nome %></td>
        <td><%= professore.disciplina %></td>
        <td><%= professore.descricao.html_safe %></td>
        <td><%= professore.nucleo_id %></td>
        <td><%= link_to 'Show', professore %></td>
        <td><%= link_to 'Edit', edit_professore_path(professore) %></td>
        <td><%= link_to 'Destroy', professore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= render 'form' %>
  </tbody>
</table>

<br>

<%= link_to 'New Professore', new_professore_path %>

app/views/professores/new.html.erb
<h1>Cadastrar professor</h1>

<%= render 'form' %>

<%= link_to 'voltar', professores_path,class:"btn btn-default" %>

app/views/professores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professore.nome %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @professore.disciplina %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @professore.descricao %>
</p>

<p>
  <strong>Nucleo:</strong>
  <%= @professore.nucleo_id %>
</p>

<%= image_tag @professore.photo.url %>
<table class="table">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Data criacao</th>
      <th>Data prioridade</th>
       <th>Turma</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arquivos.each do |arquivo| %>
      <tr>
        <td><%= arquivo.titulo %></td>
        <td><%= arquivo.descricao.html_safe %></td>
        <td><%= arquivo.data_criacao %></td>
        <td><%= arquivo.data_prioridade %></td>
         <td><%= arquivo.define_turma arquivo.turma %></td>
        
      
        <td><%= link_to 'Mostrar', arquivo,class:"btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_arquivo_path(arquivo),class:"btn btn-warning" %></td>
        <td><%= link_to 'Apagar', arquivo, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    
    <%= render 'arquivos/form' %>
<%= link_to 'Editar', edit_professore_path(@professore),class:"btn btn-warning" %> |
<%= link_to "Voltar", nucleo_path(@professore.nucleo_id),class:"btn btn-default" %>